language: cpp
dist: bionic
sudo: true
compiler:
- gcc
os:
- linux
- windows
before_install:
  - if [ $TRAVIS_OS_NAME == "windows" ]; then export MAKE=MAKE=mingw32-make fi
script:
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make

after_success:
  - cd ..
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then rm -rf build; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then rd /s /q build; fi
